version: '3'

services:
  container:
      build: ./
      image: debian_for_local_usage:jessie
      container_name: "homework_03_${USERNAME}"
      volumes:
        - ./${USERNAME}_files:/home/${USERNAME}
      tty: true
